import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F2F2F7" },
  content: { padding: 20, paddingTop: 50, alignItems: "center" },
  headerCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
  },
  sourceTag: {
    fontSize: 11,
    fontWeight: "600",
    color: "#8E8E93",
    marginBottom: 10,
  },
  productRow: { flexDirection: "row", alignItems: "center" },
  productImage: { width: 75, height: 75, borderRadius: 8, marginRight: 14 },
  imagePlaceholder: {
    backgroundColor: "#E5E5EA",
    justifyContent: "center",
    alignItems: "center",
  },
  productInfo: { flex: 1 },
  productTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1C1C1E",
    marginBottom: 2,
  },
  productBrand: { fontSize: 14, color: "#6C6C70" },
  productQuantity: {
    fontSize: 13,
    color: "#007AFF",
    fontWeight: "600",
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "600",
    color: "#1C1C1E",
    alignSelf: "flex-start",
    marginBottom: 10,
  },
  semaphoreContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 16,
  },
  nutrientCard: {
    width: (width - 56) / 3,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    elevation: 1,
  },
  nutrientLabel: { fontSize: 12, fontWeight: "600", color: "#3A3A3C" },
  gramText: { fontSize: 11, color: "#8E8E93", marginVertical: 4 },
  badge: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
  },
  badgeText: { fontSize: 11, fontWeight: "700" },
  educationalCard: {
    width: "100%",
    backgroundColor: "#FFF4E5",
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 4,
    borderLeftColor: "#FF9500",
    marginBottom: 14,
  },
  educationalTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FF9500",
    marginBottom: 4,
  },
  educationalText: { fontSize: 13, color: "#1C1C1E", lineHeight: 18 },
  spoonRow: {
    marginTop: 8,
    backgroundColor: "#FFFFFF",
    padding: 8,
    borderRadius: 8,
  },
  spoonText: { fontSize: 13, fontWeight: "600", color: "#1C1C1E" },
  expandableCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    elevation: 1,
  },
  expandableHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  expandableTitle: { fontSize: 14, fontWeight: "600", color: "#1C1C1E" },
  arrow: { fontSize: 12, color: "#8E8E93" },
  expandableContent: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#E5E5EA",
  },
  fatItem: { fontSize: 12, color: "#3A3A3C", marginBottom: 8, lineHeight: 16 },
  bold: { fontWeight: "700" },
  infoSubtitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1C1C1E",
    marginBottom: 6,
  },
  bulletPoint: {
    fontSize: 12,
    color: "#3A3A3C",
    marginBottom: 6,
    lineHeight: 16,
  },
  sourceText: {
    fontSize: 10,
    fontStyle: "italic",
    color: "#8E8E93",
    marginTop: 4,
  },
  backButton: {
    backgroundColor: "#000000",
    paddingVertical: 14,
    borderRadius: 30,
    width: "100%",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  backButtonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "600" },
});
